---
title: "Betahaus Matching Algorithm"
output: html_notebook
---

Import and clean data

```{r}
df = read.csv("~/Downloads/Investors day data - eventbrite export 041118 .csv", stringsAsFactors = FALSE)
investors = read.csv("~/Downloads/Clean Investors Day Data - Investors(7).csv", stringsAsFactors = FALSE)
startups = df[df$Ticket.Type == "Startup", c(9, 11, 12, 13, 14, 15, 16, 17, 18)]
startups = startups[grep("Getting investment", startups$What.are.you.interested.in.), ]
```

```{r}
library(googlesheets)
gs_ls()
responses = gs_title("Betahaus Investors' Day Signups (Responses)")
suppressMessages(library(dplyr))
response = responses %>% gs_read(we = "Responses")
response$`What field are you interested in?`
responselist = lapply(gsub(" ", "", response$`What field are you interested in?`),
                        function(y){strsplit(as.character(y), fixed = TRUE, ",")})

responselist
c(startuplist, responselist)[112:length(c(startuplist, responselist))]
responsedf = data.frame(matrix(0, ncol = length(unique(unlist(startuplist))), nrow = nrow(response)))
colnames(responsedf) = unique(unlist(startuplist))
responsedf
for (i in 1:length(responselist)){for (j in 1:length(responselist[[i]][[1]]))
{responsedf[i, responselist [[i]][[1]][j]] = 1}}
responsedf


listofrankings = list()

for (i in 1:nrow(investordf)){
  relevant = responsedf[, as.numeric(investordf[i,1:48 ]) == 1]
  x = matrix(unlist(sort(rowSums(scale(center = FALSE, relevant)), decreasing = TRUE, index.return = 1)), nrow = nrow(responsedf))
  x = data.frame(x[,1], startups[x[,2], c(1,3,5,8)])
  names(x)[1:2] = c("Score", "Matched Startup")
  listofrankings[[i]] = x
}
relevant

scale(center = FALSE, relevant)
```



```{r}
startuplist = lapply(gsub(" ", "", startups$What.is.your.field.),
                     function(y){strsplit(as.character(y), fixed = TRUE, "|")})
investorlist = lapply(gsub(" ", "", investors$Field.of.interest),
                      function(y){strsplit(as.character(y), fixed = TRUE, "|")})

startupdf = data.frame(matrix(0, ncol = length(unique(unlist(startuplist))), nrow = nrow(startups)))
investordf = data.frame(matrix(0, ncol = length(unique(unlist(startuplist))), nrow = nrow(investors)))
colnames(startupdf) = unique(unlist(startuplist)); colnames(investordf) = unique(unlist(startuplist))

for (i in 1:length(startuplist)){for (j in 1:length(startuplist[[i]][[1]]))
    {startupdf[i, startuplist [[i]][[1]][j]] = 1}}
for (i in 1:length(investorlist)){for (j in 1:length(investorlist[[i]][[1]]))
  {investordf[i, investorlist[[i]][[1]][[j]]] = 1}}
```



```{r}
listofrankings = list()

for (i in 1:nrow(investordf)){
  relevant = startupdf[, as.numeric(investordf[i,1:48 ]) == 1]
  x = matrix(unlist(sort(rowSums(scale(center = FALSE, relevant)), 
                         decreasing = TRUE, index.return = 1)), nrow = nrow(startups))
  x = data.frame(x[,1], startups[x[,2], c(1,3,5,8)])
  names(x)[1:2] = c("Score", "Matched Startup")
  listofrankings[[i]] = x
}
View(listofrankings[[18]])

startups[c(37,58,68,73,74,76),]
startupdf[startupdf$Wearable == 1,]

# write.csv(listofrankings[[14]], file = "Jasmine Zang.csv")
# write.csv(listofrankings[[15]], file = "Frank Wolter.csv")
# write.csv(listofrankings[[16]], file = "Heinke Bock.csv")
write.csv(listofrankings[[17]], file = "Heinke Bock.csv")
# write.csv(listofrankings[[13]], file = "Sparkasse.csv")
```


```{r}
matches = gs_new(title = "Investor Matches")
for (i in 1:length(listofrankings)){
  matches = matches %>% 
    gs_ws_new(ws_title = ifelse(nchar(investors[i,1]) <= 30, investors[i,1], substr(investors[i,1], 1, 30)), 
              input = listofrankings[[i]],trim = TRUE, verbose = FALSE)}
```












Create a matrix of how relevant the investor is to the startup, based on field of interest

```{r}
investorfields = strsplit(investors$Field.of.interest, split = "|", fixed = TRUE)
startupfields = strsplit(as.character(startups$What.is.your.field.), split = "|", fixed = TRUE)
startupfulfil = matrix(nrow = length(startupfields), ncol = length(investorfields))

for(i in 1:length(startupfields))
  {for(j in 1:length(investorfields)){
      startupfulfil[i,j] = length(intersect(startupfields[[i]], investorfields[[j]]))/length(startupfields[[i]])}}
```

Sort the relevancy of the startups by giving them a score. This is a univariate.

```{r}
scale(startupfulfil, center = TRUE)

listofrankings = list()

# startupfulfil

for(i in 1:length(investorfields)){
  x = matrix(unlist(sort(scale(startupfulfil[,i]), decreasing = FALSE, index.return = 1)), nrow = nrow(startups))
  x = data.frame(x[,1], startups[x[,2], c(1,3,5,8)])
  names(x)[2] = paste0(investors[i,1], " matches")
  listofrankings[[i]] = x

}
```

View the data so that humans can judge.
```{r}
# View(listofrankings[[1]], title = "Innoenergy Matches")
for (i in 1:length(listofrankings)){View(listofrankings[[i]])}


write.csv(listofrankings[[14]], "Sparkasse matches.csv")
w```
Export to each page of a xlsx
```{r}

```

